// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXucuQqV8qpOYSRTYRCXqjP9XTjvnU3Yg',
    appId: '1:171166277974:web:9a7673e23a80c6b387f6f7',
    messagingSenderId: '171166277974',
    projectId: 'zetron-ai',
    authDomain: 'zetron-ai.firebaseapp.com',
    storageBucket: 'zetron-ai.appspot.com',
    measurementId: 'G-72VKMTJ9YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ-4x9WYeXBTCW_ZoXDYKy7nNU9h7Te4Q',
    appId: '1:171166277974:android:1c1308cdba1a39a587f6f7',
    messagingSenderId: '171166277974',
    projectId: 'zetron-ai',
    storageBucket: 'zetron-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASPgQYiACKj7sFkhpDoaHLXGXoOb83RrU',
    appId: '1:171166277974:ios:c6a27f4febefa3a187f6f7',
    messagingSenderId: '171166277974',
    projectId: 'zetron-ai',
    storageBucket: 'zetron-ai.appspot.com',
    iosBundleId: 'com.example.gptFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASPgQYiACKj7sFkhpDoaHLXGXoOb83RrU',
    appId: '1:171166277974:ios:c6a27f4febefa3a187f6f7',
    messagingSenderId: '171166277974',
    projectId: 'zetron-ai',
    storageBucket: 'zetron-ai.appspot.com',
    iosBundleId: 'com.example.gptFlutter',
  );
}
